.Dd July 1, 2022
.Dt dyld_inspect 1
.Os Darwin
.Sh NAME
.Nm dyld_inspect
.Nd "Displays dyld state of running processes"
.Sh SYNOPSIS
.Nm
.Op Fl shared_cache_uuid
.Op Fl shared_cache_address
.Op Fl shared_cache
.Op Fl p Ar pid | Fl all
.Sh DESCRIPTION
The dyld_inspect tool will display information about live dyld state in processes.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl shared_cache_uuid
Display the shared cache UUID for each inspected process.
.It Fl shared_cache_address
Display the shared cache base address in memory for each inspected process.
.It Fl shared_cache
Enable all other 
.Cm shared_cache
options (
.Fl shared_cache_uuid
,
.Fl shared_cache_address
)
.It Fl p Ar pid
Only inspect the process with the given
.Cm pid
.It Fl all
Inspect all processes
.El
